### ISSUE TITLE
Wikidata alignment info?

### ISSUE THREAD

**Issue by j6mes** [google-research-datasets/KELM-corpus#1]
Hi, thanks for releasing this dataset. It looks super useful and I'm looking at adapting it for use in a project I'm working on. 

My goal is to look at alignments between the generated corpus and Wikidata. Do you have any data that links the Wikidata identifiers (e.g.  Q12345) and properties (e.g. P1234) from Wikidata to the references used to generate the English sentences? If so, could you please release this accompanying information.

More info 
----

I'm looking at the reference sentences in `kelm_generated_corpus.jsonl` that forms the generated corpus from Wikidata. From what I read in the paper, these sentence are generated by lexicalizing the full English Wikidata KG.

I see, for example, the following sentence which has the triples separated by spaces and commas. But some it's difficult to map this back to the subject, relation and object as it's ambiguous where the boundaries between the subject relation and object are because they're only separated by spaces?

```
Valentin Lavigne member of sports team FC Lorient, FC Lorient end time 01 January 2016, FC Lorient start time 01 January 2014.
``` 

It could be interpreted as one of the two options: 
```
(Valentin Lavigne, member of, sports team FC Lorient)
(Valentin Lavigne, member of sports team, FC Lorient)
```

The only way around this I can see is to build a reverse index of everything in Wikidata and try to reverse engineer the mapping from your reference sentences back on to Wikidata. Although, if you had alignment data you could release, that would save me a lot of hassle.

**Comment by huseinzol05** [comment]
yep, true, hopefully we can more insight about this

**Comment by oagarwal** [comment]
The files have been updated with the entity boundaries and Wikidata IDs.
