### ISSUE TITLE
Separating the parts of the triplets in references

### ISSUE THREAD

**Issue by TevenLeScao** [google-research-datasets/KELM-corpus#3]
Hi, is there an easy way to separate the different parts of the triplets from the concatenated strung in "reference"? Since the text is concatenated and the only difference between the constituents is that the relation is in lower-case (but then the entity and value might also contain lower-case), it is not clear to automatically get all the parts with full accuracy.

**Comment by oagarwal** [comment]
The files have been updated with the entity boundaries and Wikidata IDs.
